const infos = {
  meals: [
    {
      idMeal: 1,
      strMeal: "Chicken Karaage",
      strCategory: "lunch",
      strRating: 4.5,
      strServes: 1,
      strDifficulty: 'beginner',
      strMealThumb: "grilled-cheese.jpg",
      strInstructions: "Add the ginger, garlic, soy sauce, sake and sugar to a bowl and whisk to combine. Add the chicken, then stir to coat evenly. Cover and refrigerate for at least 1 hour.\r\n\r\nAdd 1 inch of vegetable oil to a heavy bottomed pot and heat until the oil reaches 360 degrees F. Line a wire rack with 2 sheets of paper towels and get your tongs out. Put the potato starch in a bowl\r\n\r\nAdd a handful of chicken to the potato starch and toss to coat each piece evenly.\r\n\r\nFry the karaage in batches until the exterior is a medium brown and the chicken is cooked through. Transfer the fried chicken to the paper towel lined rack. If you want the karaage to stay crispy longer, you can fry the chicken a second time, until it's a darker color after it's cooled off once. Serve with lemon wedges.",
      strIngredient1: "Chicken thigh",
      strIngredient2: "Ginger",
      strIngredient3: "Garlic",
      strIngredient4: "Soy sauce",
      strIngredient5: "Sake",
      strIngredient6: "Granulated sugar",
      strIngredient7: "Potato starch",
      strIngredient8: "Vegetable oil",
      strIngredient9: "Lemon",
      strIngredient10: "",
      strIngredient11: "",
      strIngredient12: "",
      strIngredient13: "",
      strIngredient14: "",
      strIngredient15: "",
      strIngredient16: "",
      strIngredient17: "",
      strIngredient18: "",
      strIngredient19: "",
      strIngredient20: "",
      strMeasure1: "450 grams Boneless skin",
      strMeasure2: "1 tablespoon",
      strMeasure3: "1 clove",
      strMeasure4: "2 tablespoons",
      strMeasure5: "1 tablespoon",
      strMeasure6: "2 teaspoon",
      strMeasure7: "1/3 cup",
      strMeasure8: "1/3 cup",
      strMeasure9: "1/3 cup",
      strMeasure10: "",
      strMeasure11: "",
      strMeasure12: "",
      strMeasure13: "",
      strMeasure14: "",
      strMeasure15: "",
      strMeasure16: "",
      strMeasure17: "",
      strMeasure18: "",
      strMeasure19: "",
      strMeasure20: "",
    },
    {
      idMeal: 2,
      strMeal: "Greek Yogurt Fruit Bowl",
      strCategory: "breakfast",
      strRating: 4.7,
      strServes: 2,
      strDifficulty: 'intermediate',
      strMealThumb: "original-design.webp",
      strInstructions: "Add the Greek yogurt to a bowl. Top with sliced banana, berries, and drizzle honey on top.",
      strIngredient1: "cup of Greek yogurt",
      strIngredient2: "banana, sliced",
      strIngredient3: "cup of berries",
      strIngredient4: "tbsp of honey",
      strIngredient5: "",
      strIngredient6: "",
      strIngredient7: "",
      strIngredient8: "",
      strIngredient9: "",
      strIngredient10: "",
      strIngredient11: "",
      strIngredient12: "",
      strIngredient13: "",
      strIngredient14: "",
      strIngredient15: "",
      strIngredient16: "",
      strIngredient17: "",
      strIngredient18: "",
      strIngredient19: "",
      strIngredient20: "",
      strMeasure1: "1",
      strMeasure2: "1",
      strMeasure3: "1/2",
      strMeasure4: "1",
      strMeasure5: "",
      strMeasure6: "",
      strMeasure7: "",
      strMeasure8: "",
      strMeasure9: "",
      strMeasure10: "",
      strMeasure11: "",
      strMeasure12: "",
      strMeasure13: "",
      strMeasure14: "",
      strMeasure15: "",
      strMeasure16: "",
      strMeasure17: "",
      strMeasure18: "",
      strMeasure19: "",
      strMeasure20: "",
    },
    {
      idMeal: 3,
      strMeal: "Chicken Caesar Salad",
      strCategory: "lunch",
      strRating: 3.5,
      strServes: 2,
      strDifficulty: 'advanced',
      strMealThumb: "original-design.webp",
      strInstructions: "Preheat the oven to 400°F (200°C). Season the chicken breasts with salt and pepper, then bake for 20-25 minutes or until cooked through. Mix together chopped lettuce, croutons, and grated Parmesan cheese in a bowl. Slice the cooked chicken and toss it with the salad. Drizzle with Caesar dressing and enjoy!",
      strIngredient1: "chicken breasts",
      strIngredient2: "head of lettuce, chopped",
      strIngredient3: "cup of croutons",
      strIngredient4: "cup of grated Parmesan cheese",
      strIngredient5: "Caesar dressing",
      strIngredient6: "",
      strIngredient7: "",
      strIngredient8: "",
      strIngredient9: "",
      strIngredient10: "",
      strIngredient11: "",
      strIngredient12: "",
      strIngredient13: "",
      strIngredient14: "",
      strIngredient15: "",
      strIngredient16: "",
      strIngredient17: "",
      strIngredient18: "",
      strIngredient19: "",
      strIngredient20: "",
      strMeasure1: "2",
      strMeasure2: "1",
      strMeasure3: "1/2",
      strMeasure4: "1/4",
      strMeasure5: "",
      strMeasure6: "",
      strMeasure7: "",
      strMeasure8: "",
      strMeasure9: "",
      strMeasure10: "",
      strMeasure11: "",
      strMeasure12: "",
      strMeasure13: "",
      strMeasure14: "",
      strMeasure15: "",
      strMeasure16: "",
      strMeasure17: "",
      strMeasure18: "",
      strMeasure19: "",
      strMeasure20: "",
    },
    {
      idMeal: 4,
      strMeal: "Grilled Cheese Sandwich",
      strCategory: "supper",
      strRating: '',
      strServes: 1,
      strDifficulty: 'advanced',
      strMealThumb: "grilled-cheese.jpg",
      strInstructions: "Heat a non-stick pan over medium heat. Butter one side of each slice of bread. Place one slice of bread, butter-side down, in the pan. Sprinkle shredded cheddar cheese on top of the bread slice in the pan. Top with the other slice of bread, butter-side up. Grill the sandwich until both sides are golden brown and the cheese is melted. Cut the sandwich in half and enjoy!",
      strIngredient1: "slices of bread",
      strIngredient2: "cup of shredded cheddar cheese",
      strIngredient3: "Butter",
      strIngredient4: "",
      strIngredient5: "",
      strIngredient6: "",
      strIngredient7: "",
      strIngredient8: "",
      strIngredient9: "",
      strIngredient10: "",
      strIngredient11: "",
      strIngredient12: "",
      strIngredient13: "",
      strIngredient14: "",
      strIngredient15: "",
      strIngredient16: "",
      strIngredient17: "",
      strIngredient18: "",
      strIngredient19: "",
      strIngredient20: "",
      strMeasure1: "2",
      strMeasure2: "1/4",
      strMeasure3: "",
      strMeasure4: "",
      strMeasure5: "",
      strMeasure6: "",
      strMeasure7: "",
      strMeasure8: "",
      strMeasure9: "",
      strMeasure10: "",
      strMeasure11: "",
      strMeasure12: "",
      strMeasure13: "",
      strMeasure14: "",
      strMeasure15: "",
      strMeasure16: "",
      strMeasure17: "",
      strMeasure18: "",
      strMeasure19: "",
      strMeasure20: "",
    },
  ],
}


export default infos;



